apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-fast-food-production-config
  namespace: default
  labels:
    app: fiap-fast-food-app-production
data:
  PORT: "3333"
  AWS_REGION: "us-west-2"
  SQS_PRODUCTION_QUEUE_URL: ${SQS_PRODUCTION_QUEUE_URL}
  SNS_PRODUCTION_TOPIC_ARN: ${SNS_PRODUCTION_TOPIC_ARN}
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "terraformAdmin"
  POSTGRES_DB: "fiapdbPostgres"
