apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiap-fast-food-production-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /production
            pathType: Prefix
            backend:
              service:
                name: fiap-fast-food-production-service
                port:
                  number: 80
