apiVersion: v1
kind: Secret
metadata:
  name: fiap-fast-food-secret
  namespace: default
  labels:
    app: fiap-fast-food-app-production
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${BASE64_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${BASE64_SECRET_ACCESS_KEY}
  AWS_SESSION_TOKEN: ${BASE64_SESSION_TOKEN}
  MYSQL_PASSWORD: ${BASE64_MYSQL_PASSWORD}
  MYSQL_HOST: ${BASE64_MYSQL_HOST}
